root = "."
tmp_dir = "tmp"

[build]
# comento a linha a baixo caso queira debugar
# cmd = "go build -o ./tmp/main ./cmd/srv-alpha_fup/"

# descomente as linhas a baixo caso queira debugar
cmd = "go build -gcflags='all=-N -l' -o ./tmp/main ./cmd/srv-alpha_fup/"
full_bin = "dlv exec --accept-multiclient --headless --continue --listen :2345 --api-version 2 ./tmp/main"

bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
delay = 1000
kill_delay = 10
